services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: app
            dockerfile: Dockerfile
        container_name: "${APP_NAME}-app"
        restart: always
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - my-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: serverName=Docker


    nginx:
        image: nginx:alpine
        container_name: "${APP_NAME}-nginx"
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - my-network

    db:
      image: mysql:5.7
      container_name: "${APP_NAME}-mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      command: --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
        - "6030:3306"
      volumes:
        - ./mysql/init:/docker-entrypoint-initdb.d
        - ./mysql/db_data:/var/lib/mysql
      networks:
        - my-network

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "${APP_NAME}-phpmyadmin"
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: "root"
        PMA_PASSWORD: "root"
        PMA_ARBITRARY: 1
        UPLOAD_LIMIT: 300M
      restart: always
      volumes:
        - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      ports:
        - 8081:80
      networks:
        - my-network


networks:
    my-network:
        driver: bridge


